config/routes.rb
Rails.application.routes.draw do
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'pages#home'
  get 'about', to:'pages#about'
  get 'calendar', to:'pages#calendar'
  resources :contacts, only: :create
  get 'contact-paul', to:'contacts#new', as:'new-contact'
  resources :bookings, only: :create 
  get 'booking', to:'bookings#new', as: 'new-booking'
  get 'songlist', to: 'pages#songlist'
  get 'photos', to: 'pages#photos'
  get 'video', to: 'pages#video'
  get 'lessons',to: 'pages#lessons'
  get 'faq', to: 'pages#faq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  # Booking form validations
  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true
  validates :phone, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # Contact form validations
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @bookings = Booking.new
    end
    
    def create
        # Mass assignment of form fields into Booking object
        @booking = Booking.new(booking_params)
        
        # Save the contact object to the database
        if @booking.save
          
          # Store form field parameters into local variables
          fname = params[:booking][:fname]
          lname = params[:booking][:lname]
          phone = params[:booking][:phone]
          email = params[:booking][:email]
          company = params[:booking][:company]
          eventtype = params[:booking][:eventtype]
          date = params[:booking][:date]
          details = params[:booking][:details]
          
          # Plug variables into Contact Mailer email method and send email
          BookingMailer.booking_email(fname,lname,phone,email,company,eventtype,date,details).deliver          
          
          # Store success method into flash hash
          # and redirect to the 'new' action
          flash[:success] = "Booking request submitted. Please allow 48 hours for a response."
          redirect_to new_booking_path
        else
          
          # If Booking object doesn't save,
          # store errors in Flash hash and redirect to 'new path'
          flash[:danger] = @booking.errors.full_messages.join(", ")
         redirect_to new_booking_path
        end
    end
    
    private
  
        # To collect data from form, we need to use strong parameters
        # and whitelist form fields
        def booking_params
         params.require(:booking).permit(:fname, :lname, :phone, :email, :company, :eventtype, :date, :details)
        end
    
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   def new
       @contacts = Contact.new
   end
   # POST request to /contacts
  def create
    
    # Mass assignment of form fields into Contact object
    @contact = Contact.new(contact_params)
    
    # Save the contact object to the database
    if @contact.save
      
      # Store form field parameters into local variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      
      # Plug variables into Contact Mailer email method and send email
      ContactMailer.contact_email(name,email,body).deliver
      
      # Store success method into flash hash
      # and redirect to the 'new' action
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      
      # If Contact object doesn't save,
      # store errors in Flash hash and redirect to 'new path'
      flash[:danger] = @contact.errors.full_messages.join(", ")
     redirect_to new_contact_path
    end
  end
  
  private
  
    # To collect data from form, we need to use strong parameters
    # and whitelist form fields
    def contact_params
     params.require(:contact).permit(:name, :email, :comments)
    end
   
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_time, :end_time)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
    end
    
    def about
    end

    def calendar
    end
    
    def songlist
    end
    
    def photos
    end
    
    def video
    end
    
    def lessons
    end
    
    def faq
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/bookings/new.html.erb
<% content_for :title, "Booking" %>


<script>
  $( function() {
      $.datepicker.setDefaults({minDate: 0, maxDate: "+24M"});
      $( "#datepicker" ).datepicker();
  } );
</script>
  
<div class="container">
  <div class="row">
    <h1 class="text-center gold-shadow">Booking </h1>
    <div class="col-md-6 col-md-offset-3">
      <div id="booking-note" class="text-center">
        <p>
          <em><hr>Due to the varying requirements to be considered for each event, it is best to call for an accurate price quote<hr>
          </em>
        </p>
        <p>
          <i class="fa fa-phone"></i> <b>847.791.0512</b>
        </p>
      </div>
    </div>
    
    <hr>
    <div class="col-md-6 col-md-offset-3">
      <div class="well">
        
        <%= form_for @bookings do |f| %>
  
          <div class="form-group has-feedback">
            <%= f.label ("First Name *") %>
            <%= f.text_field :fname, class:'form-control' %>
            <i class="fa fa-user form-control-feedback "></i>
          </div>
          <div class="form-group has-feedback">
            <%= f.label ("Last Name *") %>
            <%= f.text_field :lname, class:'form-control' %>
            <i class="fa fa-user form-control-feedback "></i>
          </div>
          <div class="form-group has-feedback">
            <%= f.label ("Phone Number *") %>
            <%= f.phone_field :phone, class:'form-control' %>
            <i class="fa fa-phone form-control-feedback "></i>
          </div>
          <div class="form-group has-feedback">
            <%= f.label ("E-mail *") %>
            <%= f.text_field :email, class:'form-control' %>
            <i class="fa fa-envelope form-control-feedback "></i>
          </div>
          <div class="form-group has-feedback">
            <%= f.label ("Company") %>
            <%= f.text_field :company, class:'form-control', placeholder: "(optional)" %>
            <i class="fa fa-briefcase form-control-feedback "></i>
          </div>
          <div class="form-group has-feedback">
            <%= f.label ("Event Date") %>
            <%= f.text_field :date, id: 'datepicker', class:'form-control', style:'cursor:pointer', placeholder: "Click here to select date" %>
            <i class="fa fa-calendar form-control-feedback "></i>
          </div>
          <div class="form-group">
            <%= f.label :Event_type %>
            <% ['Wedding', 'Bar/Bat Mizvah', 'Corporate Event', 'Senior Living', 'Celebration (birthday, anniversary, etc)', 'Other (Please provide details below)'].each do |etype| %>
              <br>
              <%= f.radio_button :eventtype, etype %>
              <%= etype.humanize %>
              <br>

            <% end %>
          </div>
          <div class="form-group has-feedback">
            <%= f.label :details %>
            <%= f.text_area :details, style: 'max-width:100%', class:'form-control', placeholder: "Venue, Song Requests, Budget, Theme, etc" %>
            <i class="fa fa-comment form-control-feedback "></i>
          </div>
          <div class="form-group">
            <%= f.submit "Submit", class:'btn btn-primary btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<% content_for :title, "Contact" %>

<div class="container">
  <div class="row" >
    <h1 class="text-center gold-shadow">Contact Paul</h1>
    
    <div class="col-md-6 col-md-offset-3">
      <div class="well">

              <%= form_for @contacts do |f| %>
                <div class="form-group has-feedback">
                  <%= f.label :name %>
                  <%= f.text_field :name, class:'form-control' %>
                  <i class="fa fa-user form-control-feedback "></i>
                </div>
                <div class="form-group has-feedback">
                  <%= f.label :email %>
                  <%= f.text_field :email, class:'form-control' %>
                  <i class="fa fa-envelope form-control-feedback "></i>

                </div>
                <div class="form-group has-feedback">
                  <%= f.label :comments %>
                  <%= f.text_area :comments, style: 'max-width:100%', class:'form-control' %>
                  <i class="fa fa-comment form-control-feedback "></i>

                </div>
                <div class="form-group">
                  <%= f.submit "Submit", class:'btn btn-default btn-primary' %>
                </div>
              <% end %>

      </div>
    </div>
    </div>
  </div>    

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<script>
$('#calendar').fullCalendar();
</script>

<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us">
  <head>
    
    <title>PaulGoldmanMusic | <%= yield :title %> </title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="https://res.cloudinary.com/dl4upkour/image/upload/c_scale,e_brightness:100,w_112/v1485445956/Twitch_AVATAR.ico">
    
    <link href="https://fonts.googleapis.com/css?family=Exo+2|Kanit|Bowlby+One+SC|PT+Serif|Signika+Negative|Special+Elite" rel="stylesheet">
    
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    
    
  </head>

  <body>
    
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class='container'>
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <%= link_to root_path, class:"navbar-brand", title: "Home" do %>
            Home
          <% end %>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->  
        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
          
          <ul class="nav navbar-nav navbar-right">

            <li><%= link_to "About", about_path, title: "About" %></li>
            <li><%= link_to "Calendar", calendar_path, title: "Calendar" %></li>
            <li><%= link_to "Song List", songlist_path, title: "Song List" %></li>
            <!--<li class="dropdown">-->
            <!--  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Media<span class="caret"></span></a>-->
            <!--  <ul class="dropdown-menu navbar-default" id="media-dropdown">-->
                <!--<li><%= link_to "Photos", photos_path %></li>-->
            <li><%= link_to "Videos", video_path, title: "Video" %></li>
            <li><%= link_to "FAQ", faq_path, title: "FAQ" %></li>
            <li><%= link_to "Booking", new_booking_path, title: "Booking" %></li>
              <!--</ul>-->
            <!--</li>-->
            <li><%= link_to "Contact", new_contact_path, title: "Contact" %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container flash-container">
       <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class:"alert alert-#{type}" %>
      <% end %>
    </div>

    <%= yield %>
    
    <footer>
      <div class="container">
        <div class="row text-center">
          <div id="footer-social" >
            <div class="social-popout">
              <a href="https://www.facebook.com/paulgoldmanmusic" target="blank" title="Facebook" >
                <i class="fa fa-facebook fa-3x" aria-hidden="true"></i>
                <!--<img src="https://res.cloudinary.com/dl4upkour/image/upload/v1490673674/facebook_social_logo.png" alt="Facebook"/>-->
              </a>
            </div>
            <div class="social-popout">
              <a href="https://twitter.com/goldman_paul" target="blank" alt="Twitter" title="Twitter">
                <i class="fa fa-twitter fa-3x" aria-hidden="true"></i>
              </a>
            </div>
            <div class="social-popout">
              <a href="https://youtube.com/paulgoldmanmusic" target="blank" alt="Youtube" title="Youtube">
                <i class="fa fa-youtube fa-3x" aria-hidden="true"></i>
              </a>
            </div>
            <!--<div>-->
            <!--  <a href="https://twitch.tv/paulgoldmanmusic" target="blank" alt="Twitch.tv" title="Twitch.tv">-->
            <!--    <i class="fa fa-twitch fa-3x" aria-hidden="true"></i>-->
            <!--  </a>-->
            <!--</div>-->
            <div class="social-popout">
              <a href="https://www.linkedin.com/in/paulgoldmanmusic" target="blank" alt="LinkedIn" title="LinkedIn">
                <i class="fa fa-linkedin fa-3x" aria-hidden="true"></i>
              </a>
            </div>
          </div>
          <div id="copyright-text" >
            <p class="gold">
              <a href="mailto:paul@paulgoldmanmusic.com">
                <span class="glyphicon glyphicon-envelope"></span> paul@paulgoldmanmusic.com</a>
                <br> &#169; 2017 Paul Goldman. All Rights Reserved.
            </p>
          </div>
          
        </div>
      </div>
      
    </footer>
  </body>
  
</html>

app/views/pages/about.html.erb
<% content_for :title, "About" %>


<div class="container">
  <div class="row">
    <h1 class="text-center gold-shadow">About Paul</h1>
    <div class="col-sm-12">
      <article class="aboutpage text-justify">
        <!--<section>-->
          <img id="about-img" class="img-responsive" src="https://res.cloudinary.com/dl4upkour/image/upload/v1485288226/ZeiserWedding2_xiffqb.jpg" alt="Wedding">
          <p>
          Paul Goldman is an acclaimed pianist, singer, and music instructor from Chicagoland. His incredible versatility
          is the result of lifelong musical study. A master sightreader as well as ear player, Paul has performed solo and alongside 
          Chicago's most in-demand Dueling Pianos and jobbing bands, playing at hundreds of weddings, birthdays, parties, and 
          corporate functions. 
          </p>
        <!--</section>-->
        <br>
        <p>
          Born in Moscow, Russia, Paul began playing the piano at age 4. Throughout his childhood, Paul expanded his musical understanding
          by listening to as much music as he could get his hands on. He graduated from Columbia College in 2011 with a Bachelor of 
          Music in Contemporary Urban Pop. At Columbia, Paul performed alongside many established artists including bass virtuoso 
          Christian McBride, drummer Peter Erskine (Weather Report), Fred Wesley (trombonist for James Brown), Kevin Eubanks (leader
          of the Tonight Show Band), and Charlie Sexton (guitarist for Bob Dylan).
        </p>
        <br>
        <p>
          Paul has worked with an eclectic selection of musicians in the Chicagoland area.
          Here are some of the great local artists Paul has worked with: Classic rock cover band <a href="https://www.secondtimearoundmusic.com/" target="blank">Second Time Around</a>, 
          Russian Cabaret singer <a href="https://www.youtube.com/watch?v=RvJD36oYcZ4" target="blank">Tanya Melamed</a>, 
          Rapper <a href="https://rhymesayers.com/artists/psalmone" target="blank">Psalm One</a>, 
          Klezmer band <a href="http://klezmerband.com/" target="blank">Maxwell Street Klezmer Band</a>, 
          Alternative/Reggae/Jam band <a href="https://soundcloud.com/flowtheory" target="blank">Flow Theory</a>, 
          and Argentine Bandoneon virtuoso <a href="https://www.youtube.com/watch?v=zBtdAWUOsNM" target="blank">Richard Scofano</a>.
        </p>
        <!--<br>-->
        <!--<ul>-->
        <!--  <li class="about-artist-list">| Classic rock cover band -->
        <!--    <a href="https://www.secondtimearoundmusic.com/" target="blank">Second Time Around</a> | </li>-->
        <!--  <li class="about-artist-list">Russian Cabaret singer -->
        <!--    <a href="https://www.youtube.com/watch?v=RvJD36oYcZ4" target="blank">Tanya Melamed</a> | </li>-->
        <!--  <li class="about-artist-list">Rapper -->
        <!--    <a href="https://rhymesayers.com/artists/psalmone" target="blank">Psalm One</a> | </li>-->
        <!--  <li class="about-artist-list">Klezmer band -->
        <!--    <a href="http://klezmerband.com/" target="blank">Maxwell Street Klezmer Band</a> | </li>-->
        <!--  <li class="about-artist-list">Alternative/Jam/Reggae band -->
        <!--    <a href="https://soundcloud.com/flowtheory" target="blank">Flow Theory</a> | </li>-->
        <!--  <li class="about-artist-list">Argentine Bandoneon virtuoso -->
        <!--    <a href="https://www.youtube.com/watch?v=zBtdAWUOsNM" target="blank">Richard Scofano</a> |</li>-->
        <!--<br>-->
        <br>
        <p>
          Some of the restaurants and bars Paul has played at include: <a href="http://www.thezebralounge.net/">The Zebra Lounge</a>,
          <a href="http://www.seasons52.com/locations/il/oak-brook/oak-brook/4522">Seasons 52</a>, 
          <a href="http://www.redheadpianobar.com/">The Redhead</a>, <a href="http://www.hugosfrogbar.com/">Hugo's Frog Bar</a>,
          <a href="http://www.citywinery.com/chicago/">City Winery</a>, <a href="https://www.riverscasino.com/desplaines/">Rivers Casino</a>,
          and MANY more.

          Paul currently teaches piano & music theory lessons, performs at dozens of Chicagoland senior living communities, and is a regular entertainer at the 
          <a href="https://www.cinemark.com/vip-the-rhythm-room.aspx" target="blank">Rhythm Room</a> (Evanston) and 
          <a href="http://www.bigshotpianolounge.com/" target="blank">Big Shot Piano Lounge</a> (Arlington Heights). Make sure to 
          check out the calendar to find out when you can see Paul perform next!
        </p>
        <br>

      </article>
    </div>
  </div>
</div>

app/views/pages/calendar.html.erb
<% content_for :title, "Calendar" %>

<script>
$(function(){
    $('#calendar').fullCalendar({
        googleCalendarApiKey: 'AIzaSyBqh_ikWkk1ZCa8_dGxXcZvx_bOJBA0Fes',
        events: {
            googleCalendarId: 'gm4cesvlmj3m52ctp22u270t50@group.calendar.google.com'
        }
    });
})
    
</script>

<div class="container">
    <div class="row">
        <h1 class="text-center gold-shadow">Upcoming Shows</h1>
        <div id="calendar">
            
        </div>
        <!--<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=gm4cesvlmj3m52ctp22u270t50%40group.calendar.google.com&amp;color=%23711616&amp;ctz=America%2FChicago" style="border:solid 1px #777" width="100%" height="600" frameborder="0" scrolling="no"></iframe>-->
    </div>
</div>

app/views/pages/faq.html.erb
<% content_for :title, "FAQ" %>

<script>
    $(function() {
        var acc = document.getElementsByClassName("accordion");
        var i;
        
        for (i = 0; i < acc.length; i++) {
          acc[i].onclick = function() {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.maxHeight){
              panel.style.maxHeight = null;
            } else {
              panel.style.maxHeight = panel.scrollHeight + "px";
            } 
          }
        }
    });
</script>

<div class="container">
    <div class="row">
        <h1 class="text-center gold-shadow">FAQ</h1>
        <div class="col-md-6 col-md-offset-3">
            <button class="accordion accordion-question">What styles of music can you play?</button>
            <div class="panel">
              <p> All of them! I cover Top 40, Pop, Classic & Hard Rock, Electronic, Soul, Disco, R&B, Country, Classical, European, 
              Jewish, Jazz, Latin, and more! Check out the <a href="/songlist">song list</a> for a more detailed list.</p>
            </div>
            
            <button class="accordion accordion-question">Can I see you perform live before deciding to book?</button>
            <div class="panel">
              <p>Of course! In addition to seeing me at any of my <a href="/calendar">public shows</a>, I happily offer
              a FREE 1-on-1 video chat session with all prospective clients (using Skype, Facetime, or Facebook Video) at
              any time prior to booking. You will get to see and hear me play whatever you'd like, chat face to face, and 
              discuss any questions or event details you'd like. </p>
              <p>This way, you can rest assured as to the quality of music your event would be getting. </p>
            </div>
            
            <button class="accordion accordion-question">There are songs I want played at my event which are not on your 
            song list. Are you able to learn a piece of music for me?</button>
            <div class="panel">
              <p> Absolutely! I am always happy to learn new music and expand my repertoire. I'm also happy to take requests from you or your guests 
              throughout your event.</p>
            </div>
            
            <button class="accordion accordion-question">What equipment can you provide to an event?</button>
            <div class="panel">
              <p>I can provide a <a href="http://a.co/co6a85f" target="blank">Nord Stage 2</a> or 
              <a href="http://a.co/6LKNpzn" target="blank">Casio Privia PX-5S</a> keyboard, 
              a <a href="http://a.co/9uSeQNP" target="blank">QSC K10</a> speaker, a 
              <a href="http://a.co/70erNu7" target="blank">Shure Beta SM58</a> microphone, along with any necessary accessories. 
              I'm also happy to play on any piano or keyboard that you provide. </p>
            </div>
            
            <button class="accordion accordion-question">Are you accepting any piano students?</button>
            <div class="panel">
              <p>I am currently accepting a limited number of intermediate-advanced piano students. Please 
              <a href="/contact-paul">contact</a> me for more details. </p>
            </div>
            
            <button class="accordion accordion-question">What forms of payment do you accept?</button>
            <div class="panel">
              <p>I currently accept cash, check, Chase Quikpay, and Paypal. </p>
            </div>
            
            <button class="accordion accordion-question">Do you require a deposit?</button>
            <div class="panel">
              <p>I generally require a 20% deposit to reserve the date. </p>
            </div>
             
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<% content_for :title, "Home" %>

<div id="home-image">
    
    
    <!--<img class="home-image" src="https://res.cloudinary.com/dl4upkour/image/upload/c_scale,w_1507/v1485288229/PaulGoldmanMainCROPPED.jpg" alt="home-image" >-->
    <div class="container">
        <div class="jumbotron text-center vertical-center">
            <!--<img src="https://res.cloudinary.com/dl4upkour/image/upload/v1485445956/Twitch_BANNER.png">-->
            <div container>
            <h1 id="home-name" >Paul Goldman</h1>
            <h3 id="home-sub-title"><span class="white"> | </span>Music Professional 
                                    <span class="white"> | </span>
            </div>
        </div>
    </div>
</div>

app/views/pages/lessons.html.erb
<div class="container text-center">
  <div class="row">
    <h1>Lessons</h1>
  </div>
</div>

app/views/pages/songlist.html.erb
<% content_for :title, "Song List" %>

<div class="container">
    <div class="row">
        <h1 class="text-center gold-shadow">Song List</h1>
        <div id="songlist">
      
            <!-- Place this tag where you want the Awesome Table Widget to render -->
            <div data-type="AwesomeTableView" data-viewID="-Kg1fd6GWQQHUJthccjt">
                
            </div>
    
        </div>
    </div>
</div>
<!-- Place this tag in your head or just before your close body tag. -->
<!--<script src="https://awesome-table.com/AwesomeTableInclude.js"></script>-->